name: Terraform Infrastructure CI/CD

on:

  pull_request:
    branches:
      - sandbox
      - production

  push:
    branches:
      - sandbox
      - production

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:

  terraform:

    runs-on: ubuntu-latest

    environment: ${{ github.ref_name }}


    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::565393071767:role/GIthuActions-CICD-RemoteInfra
          aws-region: ap-south-1

      - name: Verify AWS Identity
        run: aws sts get-caller-identity

      - name: Terraform Init
        working-directory: environments/${{ github.ref_name }}
        run: terraform init

      - name: Terraform Validate
        working-directory: environments/${{ github.ref_name }}
        run: terraform validate

      - name: Terraform Plan
        working-directory: environments/${{ github.ref_name }}
        run: terraform plan

      - name: Terraform Apply
        working-directory: environments/${{ github.ref_name }}
        run: terraform apply
      