name: Terraform Infrastructure CI/CD

on:

  pull_request:
    branches:
      - sandbox
      - production

  push:
    branches:
      - sandbox
      - production

permissions:
  id-token: write
  contents: read

jobs:

  terraform:

    runs-on: ubuntu-latest

    environment: ${{ github.ref_name }}

    env:
      TF_VAR_bucket_name: ${{ vars.TF_VAR_bucket_name }}
      TF_VAR_dynamodb_table_name: ${{ vars.TF_VAR_dynamodb_table_name }}
      TF_VAR_hash_key: ${{ secrets.TF_VAR_hash_key }}
      TF_VAR_enviornment: ${{ vars.TF_VAR_enviornment }}
      TF_VAR_region: ${{ vars.TF_VAR_region }}

    defaults:
      run:
        working-directory: environments/${{ github.ref_name }}

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::565393071767:role/GIthuActions-CICD-RemoteInfra
          aws-region: ap-south-1

      - name: Verify AWS Identity
        run: aws sts get-caller-identity

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve